// Generated by heuristic-toolkit/tools/bundle.py. Do not edit.
// Source: main.cpp

// AHC070 pre-contest scaffold. Created and published before 2026-08-29 15:00 JST.
// Published toolkit: https://github.com/Shibungi/heuristic-toolkit/tree/2d90ab3f4d7c05ad2434ec5ff0767fa07009c64b
// Add a fixed file URL beside every pre-published AI-assisted component actually used.

#include <bits/stdc++.h>

using namespace std;

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  // コンテスト開始後に、問題文を読んだ本人が次の順で実装する。
  // 1. 入力と出力だけを通す。
  // 2. 必ずvalidな最小解を作る。
  // 3. greedy baselineを作り、固定seedでスコアを保存する。
  // 4. 差分評価をrandomized testで検証してから探索を足す。
  // 5. 使用した公開済みライブラリの固定URLを該当箇所へ残す。

  return 0;
}
