#!/usr/bin/env python3
"""Flatten project-local C/C++ includes into one AtCoder submission file."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


LOCAL_INCLUDE = re.compile(r'^(\s*)#\s*include\s*"([^"]+)"\s*(?://.*)?$')
PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\s*(?://.*)?$')


class BundleError(RuntimeError):
    pass


class Bundler:
    def __init__(self, include_dirs: list[Path]) -> None:
        self.include_dirs = [path.resolve() for path in include_dirs]
        self.once_files: set[Path] = set()
        self.active: list[Path] = []

    def resolve_include(self, name: str, including: Path) -> Path:
        candidates = [including.parent / name]
        candidates.extend(directory / name for directory in self.include_dirs)
        for candidate in candidates:
            if candidate.is_file():
                return candidate.resolve()
        searched = "\n  ".join(str(path) for path in candidates)
        raise BundleError(
            f'local include "{name}" referenced by {including} was not found; searched:\n  {searched}'
        )

    @staticmethod
    def display(path: Path) -> str:
        try:
            return path.relative_to(Path.cwd()).as_posix()
        except ValueError:
            return path.as_posix()

    def expand(self, path: Path, is_root: bool = False) -> list[str]:
        path = path.resolve()
        if path in self.once_files:
            return [f"// skipped duplicate local include: {self.display(path)}\n"]
        if path in self.active:
            cycle = " -> ".join(self.display(p) for p in [*self.active, path])
            return [f"// skipped cyclic local include: {cycle}\n"]

        try:
            lines = path.read_text(encoding="utf-8-sig").splitlines(keepends=True)
        except OSError as exc:
            raise BundleError(f"cannot read {path}: {exc}") from exc

        has_pragma_once = any(PRAGMA_ONCE.match(line.rstrip("\r\n")) for line in lines)
        if has_pragma_once:
            self.once_files.add(path)
        self.active.append(path)
        output: list[str] = []
        if not is_root:
            output.append(f"\n// BEGIN LOCAL INCLUDE: {self.display(path)}\n")

        try:
            for line in lines:
                stripped = line.rstrip("\r\n")
                if PRAGMA_ONCE.match(stripped):
                    continue
                match = LOCAL_INCLUDE.match(stripped)
                if not match:
                    output.append(line if line.endswith(("\n", "\r")) else line + "\n")
                    continue
                included = self.resolve_include(match.group(2), path)
                output.extend(self.expand(included))
        finally:
            self.active.pop()

        if not is_root:
            output.append(f"// END LOCAL INCLUDE: {self.display(path)}\n")
        return output

    def bundle(self, source: Path) -> str:
        source = source.resolve()
        if not source.is_file():
            raise BundleError(f"source does not exist: {source}")
        banner = [
            "// Generated by heuristic-toolkit/tools/bundle.py. Do not edit.\n",
            f"// Source: {self.display(source)}\n\n",
        ]
        return "".join([*banner, *self.expand(source, is_root=True)])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Expand local #include "..." directives into one C++ submission file.'
    )
    parser.add_argument("source", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument(
        "-I", "--include-dir", action="append", type=Path, default=[],
        help="additional directory for quoted includes (repeatable)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source, output = args.source.resolve(), args.output.resolve()
    if source == output:
        print("bundle error: source and output must be different files", file=sys.stderr)
        return 2
    try:
        bundled = Bundler(args.include_dir).bundle(source)
    except BundleError as exc:
        print(f"bundle error: {exc}", file=sys.stderr)
        return 2
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(bundled, encoding="utf-8", newline="\n")
    print(f"bundled {source} -> {output} ({len(bundled.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
